config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "static_pages#home"
  match "/help", :to => "static_pages#help", :as => :help
  match "/about", :to => "static_pages#about", :as => :about
  match "/contact", :to => "static_pages#contact", :as => :contact
  
  match "/signup", :to => "users#new", :as => :signup
  match '/signin',  to: 'sessions#new', :as => :signin
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :password, presence: true, length: { minimum: 6}
  validates :password_confirmation, presence: true
  
  before_save { email.downcase! }
  before_save :create_remember_token
  
  private
    
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
   
  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
    
  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or(user)
    else
      flash[:error] = I18n.t('flash.auth')
      render "new"
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def home
  end
  
  def about
    
  end
  
  def contact
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update] 
  before_filter :correct_user, only: [:edit, :update] 
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = t"flash.profile_updated"
      sign_in @user
      redirect_to @user
    else
      render "edit"  
    end
  end
  
  def edit
    if(!current_user.nil?)
      @user = current_user 
      #User.find(params[:id])
    else
      redirect_to root_url
    end
  end
  
  def destroy
    if current_user.admin? && !current_user?(User.find(params[:id])) 
      User.find(params[:id]).destroy
      flash[:success] = t("flash.user_destroyed")
      redirect_to users_url
    else 
      redirect_to users_url
    end
  end
  
  private
    
    def signed_in_user
      store_location
      redirect_to signin_url, notice: I18n.t("flash.signin") unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = t 'title'
    return base_title if page_title.empty?
    return "#{base_title} | #{page_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.url
  end
  
  def sign_out
    self.current_user.save(validate: false)
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to t('footer.about'), about_path %></li>
      <li><%= link_to t('footer.contact'), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t('footer.news') %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%=link_to t('header.title'), root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to t('header.home'), root_path %></li>
						<li><%= link_to t('header.help'), help_path %></li>
						<% if signed_in? %>
							<li><%= link_to t('header.users'), users_path %></li>
							<li>
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<%= t('header.account')%> <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to t('header.profile'), current_user %></li>
									<li><%= link_to t('header.settings'), edit_user_path(current_user) %></li>
									<li class="divider"></li>
									<li><%= link_to t('header.signout'), signout_path, method: "delete" %></li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to t('header.signin'), signin_path %></li>
						<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%=full_title(yield(:title))%></title>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= render "layouts/shim" %>
</head>
<body>
	<%= render "layouts/header" %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, t('.title')) %>
    <h1><%= t'.title' %></h1>
    <p>
      <%= t'.welcome_html' %>
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, t('.title')) %>
    <h1><%= t'.title'%></h1>
	<p>
      <%= t'.welcome_html' %>
	</p>

app/views/static_pages/help.html.erb
<% provide(:title, t('.title')) %>
    <h1><%= t '.title' %></h1>
    <p>
      <%= t '.welcome_html' %>
    </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
    <h1><%= t '.title' %></h1>
    <h2>
      <%= t '.welcome_html'%>
    </h2>
    
    <%= link_to t('.signup'), signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/_user.html.erb
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      <div class="email">
      	<%= link_to user.email, "mailto: #{user.email}" %>
      	<% if current_user.admin? && !current_user?(user) %>
      		| <%= link_to t('users.index.delete'), user, method: :delete, data: {confirm: t('users.index.delete_message')} %>
      	<% end %>
      </div>
    </li>

app/views/users/edit.html.erb
<% provide(:title, t('.title')) %>
<h1><%= t'.welcome'%></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, t('.confirm') %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit t('.save'), class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails"><%= t'.change'%></a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t('.title')) %>
<h1><%=t('.title')%></h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, t('.title')) %>
<h1><%= t'.title'%></h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :email %>
		<%= f.text_field :email %>
		
		<%= f.label :password %>
		<%= f.password_field :password %>
		
		<%= f.label :password_confirmation, t('.confirm') %>
		<%= f.password_field :password_confirmation %>
		
		<%= f.submit t('.createaccount'), class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>